export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";
export const AUTH_UNREGISTERED_USER = "AUTH_UNREGISTERED_USER";

export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";
export const AUTH_GET_STATUS_NONE = "AUTH_GET_STATUS_NONE";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

/* MEMO */
export const MEMO_ADD_POST = "MEMO_ADD_POST";
export const MEMO_ADD_POST_SUCCESS = "MEMO_ADD_POST_SUCCESS";
export const MEMO_ADD_POST_FAILURE = "MEMO_ADD_POST_FAILURE";

export const MEMO_LIST_POST = "MEMO_LIST_POST";
export const MEMO_LIST_POST_SUCCESS = "MEMO_LIST_POST_SUCCESS";
export const MEMO_LIST_POST_FAILURE = "MEMO_LIST_POST_FAILURE";
export const MEMO_CLEAR = "MEMO_CLEAR";

export const MEMO_UPDATE = "MEMO_UPDATE";
export const MEMO_UPDATE_SUCCESS = "MEMO_UPDATE_SUCCESS";
export const MEMO_UPDATE_FAILURE = "MEMO_UPDATE_FAILURE";

export const MEMO_DELETE = "MEMO_DELETE";
export const MEMO_DELETE_SUCCESS = "MEMO_DELETE_SUCCESS";
export const MEMO_DELETE_FAILURE = "MEMO_DELETE_FAILURE";

export const MEMO_DETAIL_POST_SUCCESS = "MEMO_DETAIL_POST_SUCCESS";
export const MEMO_DETAIL_POST_FAILURE = "MEMO_DETAIL_POST_FAILURE";
export const MEMO_DETAIL_CLEAR = "MEMO_DETAIL_CLEAR";
